### ISSUE TITLE
Can't connect KSM to Gitlab

### ISSUE THREAD

**Issue by Flooze-IT** [conduktor/kafka-security-manager#124]
``Hi everyone,

I want to connect KSM to my personal Gitlab but when i run ksm Docker image (with Kubernetes). 
Nothing happened and the pod is complete.
Some logs :
![image](https://user-images.githubusercontent.com/83304595/168630260-ffa5d971-a3d7-40f0-8c07-0b78ef0377e1.png)
Kubernetes config:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-security-manager-cm
  labels:
    app: kafka-security-manager
data:
  KSM_EXTRACT_FORMAT: yaml
  KSM_EXTRACT_ENABLE: "true"
  AUTHORIZER_ZOOKEEPER_CONNECT: kafka-cluster-cp-zookeeper.tenant1.svc.cluster.local:2181
  SOURCE_CLASS: io.conduktor.ksm.source.GitLabSourceAcl
  SOURCE_GITLAB_REPOID: "2261"
  SOURCE_GITLAB_FILEPATH: xxx.yml
  SOURCE_GITLAB_BRANCH: main
  SOURCE_GITLAB_HOSTNAME: https://xxx.com/
  SOURCE_GITLAB_ACCESSTOKEN: xxx
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-security-manager
  labels:
    app: kafka-security-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-security-manager
  template:
    metadata:
      labels:
        app: kafka-security-manager
    spec:
      containers:
        - name: kafka-security-manager
          image: conduktor/kafka-security-manager:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: kafka-security-manager-cm
```

Thanks :)
